#!/bin/bash

TAPDEV="tap0"
BRIDGEDEV="bridge1"

sysctl -w net.link.ether.inet.proxyall=0
sysctl -w net.inet.ip.forwarding=0
# sysctl -w net.inet.ip.fw.enable=0

ifconfig ${BRIDGEDEV} down
ifconfig ${BRIDGEDEV} deletem ${TAPDEV}
ifconfig ${BRIDGEDEV} deletem en0
ifconfig ${BRIDGEDEV} 0.0.0.0 down
ifconfig ${BRIDGEDEV} destroy
