[package]
name = "shos"
version = "0.1.0"
authors = ["hagiwara"]
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
opt-level = 0
debug = true

[profile.release]
panic = "abort"
opt-level = 2
lto = true

[dependencies]
rlibc = "1.0.0"

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
features = ["mem"]
stage = 1

[target.i686-unknown-linux-gnu.dependencies]
asm = {path = "asm"}
